// Command generate-emoji fetches the Unicode emoji-test.txt and CLDR annotations
// to produce the embedded emoji database for emoji-picker-for-i3.
//
// Usage:
//
//	go run ./cmd/generate-emoji -- -o internal/picker/_data/emoji.txt
package main

import (
	"bufio"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/google/renameio/v2"
)

const (
	// Data from these URLs is subject to the Unicode License Agreement.
	// See https://www.unicode.org/license.txt
	emojiTestURL           = "https://unicode.org/Public/emoji/16.0/emoji-test.txt"
	cldrAnnotations        = "https://raw.githubusercontent.com/unicode-org/cldr-json/46.0.0/cldr-json/cldr-annotations-full/annotations/en/annotations.json"
	cldrDerivedAnnotations = "https://raw.githubusercontent.com/unicode-org/cldr-json/46.0.0/cldr-json/cldr-annotations-derived-full/annotationsDerived/en/annotations.json"
)

var httpClient = &http.Client{Timeout: 60 * time.Second}

type annotation struct {
	Default []string `json:"default"`
	TTS     []string `json:"tts"`
}

type cldrFile struct {
	Annotations struct {
		Annotations map[string]annotation `json:"annotations"`
	} `json:"annotations"`
}

func fetchCLDR(url string, annotations map[string]annotation) error {
	log.Printf("fetching %s", url)
	resp, err := httpClient.Get(url)
	if err != nil {
		return fmt.Errorf("fetching %s: %w", url, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("fetching %s: HTTP %d", url, resp.StatusCode)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("reading %s: %w", url, err)
	}
	var cldr cldrFile
	if err := json.Unmarshal(body, &cldr); err != nil {
		return fmt.Errorf("parsing %s: %w", url, err)
	}
	for k, v := range cldr.Annotations.Annotations {
		annotations[k] = v
	}
	log.Printf("loaded %d annotations from %s (total: %d)", len(cldr.Annotations.Annotations), url, len(annotations))
	return nil
}

func run() error {
	output := flag.String("o", "", "output file path (default: stdout)")
	flag.Parse()

	log.Printf("fetching %s", emojiTestURL)
	emojiResp, err := httpClient.Get(emojiTestURL)
	if err != nil {
		return fmt.Errorf("fetching emoji-test.txt: %w", err)
	}
	defer emojiResp.Body.Close()
	if emojiResp.StatusCode != http.StatusOK {
		return fmt.Errorf("fetching emoji-test.txt: HTTP %d", emojiResp.StatusCode)
	}

	annotations := make(map[string]annotation)

	for _, url := range []string{cldrAnnotations, cldrDerivedAnnotations} {
		if err := fetchCLDR(url, annotations); err != nil {
			return err
		}
	}

	// Parse emoji-test.txt
	type emoji struct {
		char string
		name string
	}
	var emojis []emoji

	scanner := bufio.NewScanner(emojiResp.Body)
	for scanner.Scan() {
		line := scanner.Text()
		// Skip comments and empty lines
		if strings.HasPrefix(line, "#") || strings.TrimSpace(line) == "" {
			continue
		}
		// Only fully-qualified emojis
		if !strings.Contains(line, "; fully-qualified") {
			continue
		}
		// Skip skin tone variants
		if strings.Contains(line, "skin tone") {
			continue
		}

		// Format: codepoints ; status # emoji E version name
		parts := strings.SplitN(line, "#", 2)
		if len(parts) < 2 {
			continue
		}
		after := strings.TrimSpace(parts[1])

		// Extract emoji character and name
		// Format after #: "😀 E1.0 grinning face"
		fields := strings.Fields(after)
		if len(fields) < 3 {
			continue
		}
		char := fields[0]
		// Skip the version field (E1.0, E15.1, etc.)
		nameFields := fields[2:]
		name := strings.Join(nameFields, " ")

		emojis = append(emojis, emoji{char: char, name: name})
	}
	if err := scanner.Err(); err != nil {
		return fmt.Errorf("scanning emoji-test.txt: %w", err)
	}
	if len(emojis) == 0 {
		return fmt.Errorf("parsed 0 emojis; upstream format may have changed")
	}
	log.Printf("parsed %d fully-qualified emojis (excluding skin tone variants)", len(emojis))

	// Write output
	var buf strings.Builder
	fmt.Fprintf(&buf, "# Generated by: go run ./cmd/generate-emoji -- -o internal/picker/_data/emoji.txt\n")
	fmt.Fprintf(&buf, "# Sources: Unicode emoji-test.txt 16.0, CLDR annotations 46.0.0\n")
	fmt.Fprintf(&buf, "# License: Unicode License Agreement (https://www.unicode.org/license.txt)\n")
	for _, e := range emojis {
		var tags []string
		if ann, ok := annotations[e.char]; ok {
			tags = ann.Default
		} else if ann, ok := annotations[strings.ReplaceAll(e.char, "\uFE0F", "")]; ok {
			tags = ann.Default
		}
		if len(tags) > 0 {
			fmt.Fprintf(&buf, "%s %s <small>(%s)</small>\n", e.char, e.name, strings.Join(tags, ", "))
		} else {
			fmt.Fprintf(&buf, "%s %s\n", e.char, e.name)
		}
	}

	if *output != "" {
		log.Printf("writing to %s", *output)
		if err := renameio.WriteFile(*output, []byte(buf.String()), 0644); err != nil {
			return fmt.Errorf("writing output: %w", err)
		}
	} else {
		os.Stdout.WriteString(buf.String())
	}

	log.Printf("done, wrote %d emojis", len(emojis))
	return nil
}

func main() {
	log.SetFlags(0)
	if err := run(); err != nil {
		log.Fatal(err)
	}
}
